### ISSUE TITLE
Firefox extension not working

### ISSUE THREAD

**Issue by Saladeuh** [joshxviii/animalese-typing#3]
Hi! I use Animalese Typing on my chrome and it's works fine. But on firefox (120.0.1) I get no sound. I tested it on the same sites, and the debug conskre don't say anything. Any idea?

**Comment by TheSystemGuy1337** [comment]
It was on the Firefox App Store, but Nintendo might have thrown a hissy fit and DMCA'd it off the face of the earth. As for no sound, this is an MV3 related bug as Mozilla has slaughtered MV2 in the same way as Google, crippling it. What was the last version of Firefox that this extension worked on?

**Comment by Saladeuh** [comment]
Hi! Sorry, the issue appeared when I have installing the extension, I haven't tested it before.
