### ISSUE TITLE
About audio segment source 

### ISSUE THREAD

**Issue by starmoon-1134** [joshxviii/animalese-typing#4]
The audio samples in this project are excellent. May I ask where you obtained them from, or did you create them yourself?

**Comment by joshxviii** [comment]
> The audio samples in this project are excellent. May I ask where you obtained them from, or did you create them yourself?

I got the source files from [The Sounds Resource](https://www.sounds-resource.com). They are from Animal Crossing: New Horizons. The samples were edited slightly for things like pitch variations and sometimes spliced together to make some phonetic sounds that were not in the game files. Thanks for the inquiry!

**Comment by starmoon-1134** [comment]
thank you for your quick response, it's very helpful to me.
